INSERT INTO recipes (name, description, instructions) VALUES (E'Spaghetti Carbonara', E'Classic Roman pasta with eggs, cheese, and guanciale', E'Cook pasta. Fry guanciale. Mix eggs with cheese. Toss pasta with guanciale, remove from heat, add egg mixture and toss quickly. Serve with black pepper.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'spaghetti', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'guanciale', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pecorino', E'100g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chicken Tikka Masala', E'Creamy Indian curry with grilled chicken', E'Marinate chicken in yogurt and spices. Grill or broil. Make sauce with tomatoes, cream, and spices. Add chicken and simmer.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken breast', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'yogurt', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomato puree', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'heavy cream', E'200ml');
INSERT INTO recipes (name, description, instructions) VALUES (E'Beef Tacos', E'Seasoned ground beef in crispy shells', E'Brown beef with onion and garlic. Add taco seasoning. Warm shells. Serve with lettuce, cheese, salsa, and lime.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground beef', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'taco shells', E'12');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'taco seasoning', E'1 packet');
INSERT INTO recipes (name, description, instructions) VALUES (E'Caesar Salad', E'Romaine lettuce with caesar dressing and croutons', E'Wash and chop romaine. Make dressing with anchovies, garlic, lemon, egg yolk, parmesan. Toss lettuce with dressing and croutons.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'romaine lettuce', E'2 heads');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'parmesan', E'50g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'croutons', E'1 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'Vegetable Stir Fry', E'Quick Asian-style mixed vegetables', E'Heat wok. Stir fry vegetables in batches. Add sauce. Toss and serve over rice.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mixed vegetables', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'soy sauce', E'3 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ginger', E'1 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Greek Salad', E'Fresh Mediterranean salad with feta', E'Chop tomatoes, cucumber, onion, olives. Add feta. Dress with olive oil, oregano, lemon.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cucumber', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'feta', E'200g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Beef Stew', E'Hearty slow-cooked beef and vegetables', E'Brown beef. Add onions, carrots, potatoes, broth, and herbs. Simmer 2 hours until tender.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'stewing beef', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'potatoes', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'carrots', E'3');
INSERT INTO recipes (name, description, instructions) VALUES (E'Pancakes', E'Fluffy buttermilk pancakes', E'Mix dry ingredients. Add wet. Cook on griddle until bubbles form. Flip and cook.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'2 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'buttermilk', E'2 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'2');
INSERT INTO recipes (name, description, instructions) VALUES (E'French Onion Soup', E'Caramelized onion soup with cheese toast', E'Caramelize onions. Add broth and herbs. Simmer. Top with bread and gruyere, broil.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'onions', E'6');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'beef broth', E'1.5L');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'gruyere', E'200g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chocolate Chip Cookies', E'Classic chewy chocolate chip cookies', E'Cream butter and sugar. Add eggs and vanilla. Mix in flour and chocolate chips. Bake 10-12 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'225g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chocolate chips', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'2.5 cups');
INSERT INTO recipes (name, description, instructions) VALUES (E'Grilled Salmon', E'Lemon-dill grilled salmon fillets', E'Season salmon. Grill 4-5 min per side. Squeeze lemon, top with dill.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'salmon fillets', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lemon', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'dill', E'2 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Margherita Pizza', E'Simple tomato, mozzarella, basil pizza', E'Shape dough. Top with tomato sauce, mozzarella, basil. Bake at 250°C until crust is golden.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pizza dough', E'1 ball');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mozzarella', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'basil', E'1 bunch');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chicken Noodle Soup', E'Comforting chicken soup with noodles', E'Simmer chicken with vegetables. Shred chicken. Add noodles and cook. Season with herbs.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'egg noodles', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'carrots', E'2');
INSERT INTO recipes (name, description, instructions) VALUES (E'Guacamole', E'Creamy avocado dip', E'Mash avocados. Add lime, onion, cilantro, tomato, salt.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'avocados', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lime', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cilantro', E'1/4 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'Fish Tacos', E'Crispy fish with slaw in soft tortillas', E'Bread and fry fish. Make slaw. Warm tortillas. Assemble with fish, slaw, and crema.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'white fish', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tortillas', E'8');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cabbage', E'1/4 head');
INSERT INTO recipes (name, description, instructions) VALUES (E'Lentil Soup', E'Hearty vegetarian lentil soup', E'Saute onion and carrot. Add lentils, broth, cumin. Simmer 30 min. Add lemon.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'red lentils', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'vegetable broth', E'1L');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cumin', E'1 tsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Omelette', E'Fluffy cheese omelette', E'Beat eggs. Pour into hot buttered pan. When set, add cheese, fold, slide onto plate.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'3');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cheese', E'50g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'1 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Caprese Salad', E'Tomato, mozzarella, basil with balsamic', E'Slice tomatoes and mozzarella. Arrange with basil. Drizzle olive oil and balsamic.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mozzarella', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'basil', E'1 bunch');
INSERT INTO recipes (name, description, instructions) VALUES (E'Thai Green Curry', E'Aromatic coconut curry', E'Fry curry paste. Add coconut milk, vegetables, protein. Simmer. Serve with rice.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'green curry paste', E'3 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'coconut milk', E'400ml');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken', E'400g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Bolognese', E'Rich Italian meat sauce', E'Soften onion, carrot, celery. Add beef, brown. Add wine, tomatoes. Simmer 2 hours.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground beef', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'800g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'carrot', E'1');
INSERT INTO recipes (name, description, instructions) VALUES (E'Hummus', E'Creamy chickpea dip', E'Blend chickpeas, tahini, garlic, lemon, olive oil until smooth.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chickpeas', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tahini', E'3 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lemon', E'2');
INSERT INTO recipes (name, description, instructions) VALUES (E'Pad Thai', E'Stir-fried rice noodles', E'Soak noodles. Stir fry tofu or shrimp. Add noodles and sauce. Toss with peanuts and lime.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'rice noodles', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tamarind paste', E'2 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'peanuts', E'50g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Roast Chicken', E'Crispy whole roast chicken', E'Season chicken. Roast at 200°C for 1-1.5 hours. Rest 15 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'whole chicken', E'1.5kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'olive oil', E'2 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'herbs', E'2 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Mushroom Risotto', E'Creamy rice with mushrooms', E'Toast rice. Add wine. Add broth ladle by ladle, stirring. Fold in sauteed mushrooms and parmesan.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'arborio rice', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mushrooms', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'parmesan', E'100g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Pulled Pork', E'Slow-cooked BBQ pork', E'Rub pork with spices. Slow cook 8 hours. Shred and mix with BBQ sauce.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pork shoulder', E'2kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'BBQ sauce', E'300ml');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'brown sugar', E'2 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Coleslaw', E'Creamy cabbage salad', E'Shred cabbage and carrot. Mix with mayo, vinegar, sugar. Chill before serving.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cabbage', E'1/2 head');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mayonnaise', E'1/2 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'carrot', E'1');
INSERT INTO recipes (name, description, instructions) VALUES (E'Tom Yum Soup', E'Spicy Thai soup', E'Boil broth with lemongrass, galangal, kaffir lime. Add shrimp and mushrooms. Add lime and chili.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'shrimp', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lemongrass', E'2 stalks');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mushrooms', E'100g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Quiche Lorraine', E'Bacon and cheese tart', E'Blind bake crust. Fry bacon. Mix eggs, cream, cheese. Add bacon, pour into crust. Bake 35 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pie crust', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'bacon', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'3');
INSERT INTO recipes (name, description, instructions) VALUES (E'Sushi Rolls', E'Rice and fish wrapped in nori', E'Season rice. Spread on nori. Add fillings. Roll tightly. Slice.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'sushi rice', E'2 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'nori', E'6 sheets');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'salmon', E'200g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chili Con Carne', E'Spicy bean and beef chili', E'Brown beef. Add onions, spices, tomatoes, beans. Simmer 1 hour.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground beef', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'kidney beans', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'400g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Garlic Bread', E'Crispy bread with garlic butter', E'Mix butter, garlic, parsley. Spread on bread. Bake 10 min until golden.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'baguette', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'100g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'garlic', E'4 cloves');
INSERT INTO recipes (name, description, instructions) VALUES (E'Banana Bread', E'Moist banana loaf', E'Mash bananas. Mix with flour, sugar, eggs, butter. Bake 1 hour at 180°C.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'bananas', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'2 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'sugar', E'1 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'Cobb Salad', E'Layered salad with egg, bacon, avocado', E'Arrange lettuce, chicken, bacon, egg, avocado, blue cheese in rows. Serve with dressing.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lettuce', E'1 head');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'avocado', E'1');
INSERT INTO recipes (name, description, instructions) VALUES (E'Lasagna', E'Layered pasta with meat and cheese', E'Layer sauce, noodles, ricotta, mozzarella. Repeat. Bake covered 45 min, uncover 15 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lasagna noodles', E'12');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ricotta', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground beef', E'500g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Tuna Salad', E'Canned tuna with mayo and celery', E'Drain tuna. Mix with mayo, celery, onion. Season. Serve on bread or greens.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'canned tuna', E'2 cans');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mayonnaise', E'1/4 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'celery', E'2 stalks');
INSERT INTO recipes (name, description, instructions) VALUES (E'Garlic Shrimp', E'Pan-seared shrimp in garlic butter', E'Heat butter. Add garlic. Add shrimp, cook 2 min per side. Add lemon and parsley.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'shrimp', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'garlic', E'6 cloves');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'4 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Vegetable Soup', E'Simple mixed vegetable soup', E'Saute onion. Add chopped vegetables and broth. Simmer 20 min. Season.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mixed vegetables', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'vegetable broth', E'1L');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'onion', E'1');
INSERT INTO recipes (name, description, instructions) VALUES (E'Fried Rice', E'Day-old rice with egg and vegetables', E'Scramble egg, set aside. Stir fry rice. Add vegetables, soy sauce. Add egg back.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cooked rice', E'4 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'soy sauce', E'2 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Nachos', E'Loaded tortilla chips with cheese', E'Layer chips and cheese. Bake until melted. Top with beans, salsa, guac, sour cream.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tortilla chips', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cheddar', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'black beans', E'1 can');
INSERT INTO recipes (name, description, instructions) VALUES (E'Miso Soup', E'Japanese fermented soybean soup', E'Make dashi. Add miso paste. Add tofu and seaweed. Serve with green onion.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'miso paste', E'3 tbsp');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tofu', E'150g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'wakame', E'1 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Potato Salad', E'Creamy potato salad with egg', E'Boil potatoes and eggs. Cool and chop. Mix with mayo, mustard, celery.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'potatoes', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mayonnaise', E'1/2 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggs', E'3');
INSERT INTO recipes (name, description, instructions) VALUES (E'Lemonade', E'Fresh squeezed lemonade', E'Juice lemons. Dissolve sugar in water. Mix with lemon juice. Add ice.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'lemons', E'8');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'sugar', E'1 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'water', E'1L');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chicken Wings', E'Crispy buffalo-style wings', E'Bake or fry wings until crispy. Toss in hot sauce and butter mixture.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken wings', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'hot sauce', E'1/2 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'4 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Ratatouille', E'Provencal vegetable stew', E'Layer eggplant, zucchini, tomato. Bake with garlic and herbs.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggplant', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'zucchini', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'4');
INSERT INTO recipes (name, description, instructions) VALUES (E'Eggplant Parmesan', E'Breaded eggplant with tomato and cheese', E'Slice, bread, fry eggplant. Layer with sauce and mozzarella. Bake 25 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'eggplant', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'mozzarella', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomato sauce', E'400ml');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chicken Fried Rice', E'Stir-fried rice with chicken', E'Cook chicken, set aside. Scramble egg. Stir fry rice. Add chicken, vegetables, soy sauce.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'rice', E'4 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'soy sauce', E'3 tbsp');
INSERT INTO recipes (name, description, instructions) VALUES (E'Minestrone', E'Italian vegetable and pasta soup', E'Saute vegetables. Add broth, tomatoes, beans, pasta. Simmer until pasta is done.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pasta', E'100g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cannellini beans', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'vegetables', E'500g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Cornbread', E'Southern-style cornbread', E'Mix cornmeal, flour, buttermilk, egg. Pour into hot cast iron. Bake 20 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cornmeal', E'1 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'1 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'buttermilk', E'1 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'Smoothie Bowl', E'Thick smoothie topped with fruit', E'Blend frozen fruit with banana and milk. Pour into bowl. Top with granola and fruit.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'frozen berries', E'2 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'banana', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'granola', E'1/2 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'BLT Sandwich', E'Bacon, lettuce, tomato', E'Toast bread. Layer bacon, lettuce, tomato. Add mayo. Serve.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'bacon', E'6 strips');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomato', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'bread', E'2 slices');
INSERT INTO recipes (name, description, instructions) VALUES (E'Pesto Pasta', E'Basil pesto with pasta', E'Cook pasta. Toss with pesto, parmesan, and pasta water.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pasta', E'400g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'pesto', E'1 jar');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'parmesan', E'50g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Gnocchi', E'Potato dumplings', E'Boil and mash potatoes. Mix with flour and egg. Shape, boil until float.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'potatoes', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'200g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'egg', E'1');
INSERT INTO recipes (name, description, instructions) VALUES (E'Creme Brulee', E'Creamy custard with caramelized sugar', E'Heat cream with vanilla. Whisk into egg yolks and sugar. Bake in water bath. Caramelize sugar on top.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'heavy cream', E'500ml');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'egg yolks', E'6');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'sugar', E'100g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Apple Crisp', E'Baked apples with oat topping', E'Slice apples into dish. Mix oats, flour, butter, sugar for topping. Bake 45 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'apples', E'6');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'oats', E'1 cup');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'butter', E'100g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Gazpacho', E'Cold Spanish tomato soup', E'Blend tomatoes, cucumber, pepper, bread, garlic, olive oil. Chill. Serve cold.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tomatoes', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cucumber', E'1');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'bread', E'2 slices');
INSERT INTO recipes (name, description, instructions) VALUES (E'Chicken Quesadilla', E'Cheese and chicken in tortilla', E'Layer tortilla with cheese and chicken. Fold. Cook in pan until golden and melted.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'tortillas', E'4');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'chicken', E'300g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cheese', E'200g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Shepherd''s Pie', E'Meat and vegetable topped with mashed potato', E'Cook ground meat with vegetables. Top with mashed potato. Bake 30 min.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground lamb', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'potatoes', E'1kg');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'peas', E'200g');
INSERT INTO recipes (name, description, instructions) VALUES (E'Cabbage Rolls', E'Stuffed cabbage with meat and rice', E'Blanch cabbage leaves. Fill with meat-rice mixture. Roll. Simmer in tomato sauce.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'cabbage', E'1 head');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'ground beef', E'500g');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'rice', E'1 cup');
INSERT INTO recipes (name, description, instructions) VALUES (E'Zucchini Bread', E'Moist zucchini loaf', E'Grate zucchini. Mix with flour, sugar, eggs, oil. Bake 1 hour.');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'zucchini', E'2');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'flour', E'3 cups');
INSERT INTO ingredients (recipe_id, name, quantity) VALUES (currval(pg_get_serial_sequence('recipes', 'id')), E'sugar', E'1.5 cups');