#!/usr/bin/env python3
"""Seed the database with ~55 sample recipes. Run with: python scripts/seed_recipes.py"""
import json
import urllib.request
import urllib.error

API_BASE = "http://localhost:8000"

RECIPES = [
    {"name": "Spaghetti Carbonara", "description": "Classic Roman pasta with eggs, cheese, and guanciale", "instructions": "Cook pasta. Fry guanciale. Mix eggs with cheese. Toss pasta with guanciale, remove from heat, add egg mixture and toss quickly. Serve with black pepper.", "ingredients": [{"name": "spaghetti", "quantity": "400g"}, {"name": "guanciale", "quantity": "200g"}, {"name": "eggs", "quantity": "4"}, {"name": "pecorino", "quantity": "100g"}]},
    {"name": "Chicken Tikka Masala", "description": "Creamy Indian curry with grilled chicken", "instructions": "Marinate chicken in yogurt and spices. Grill or broil. Make sauce with tomatoes, cream, and spices. Add chicken and simmer.", "ingredients": [{"name": "chicken breast", "quantity": "500g"}, {"name": "yogurt", "quantity": "200g"}, {"name": "tomato puree", "quantity": "400g"}, {"name": "heavy cream", "quantity": "200ml"}]},
    {"name": "Beef Tacos", "description": "Seasoned ground beef in crispy shells", "instructions": "Brown beef with onion and garlic. Add taco seasoning. Warm shells. Serve with lettuce, cheese, salsa, and lime.", "ingredients": [{"name": "ground beef", "quantity": "500g"}, {"name": "taco shells", "quantity": "12"}, {"name": "taco seasoning", "quantity": "1 packet"}]},
    {"name": "Caesar Salad", "description": "Romaine lettuce with caesar dressing and croutons", "instructions": "Wash and chop romaine. Make dressing with anchovies, garlic, lemon, egg yolk, parmesan. Toss lettuce with dressing and croutons.", "ingredients": [{"name": "romaine lettuce", "quantity": "2 heads"}, {"name": "parmesan", "quantity": "50g"}, {"name": "croutons", "quantity": "1 cup"}]},
    {"name": "Vegetable Stir Fry", "description": "Quick Asian-style mixed vegetables", "instructions": "Heat wok. Stir fry vegetables in batches. Add sauce. Toss and serve over rice.", "ingredients": [{"name": "mixed vegetables", "quantity": "500g"}, {"name": "soy sauce", "quantity": "3 tbsp"}, {"name": "ginger", "quantity": "1 tbsp"}]},
    {"name": "Greek Salad", "description": "Fresh Mediterranean salad with feta", "instructions": "Chop tomatoes, cucumber, onion, olives. Add feta. Dress with olive oil, oregano, lemon.", "ingredients": [{"name": "tomatoes", "quantity": "4"}, {"name": "cucumber", "quantity": "1"}, {"name": "feta", "quantity": "200g"}]},
    {"name": "Beef Stew", "description": "Hearty slow-cooked beef and vegetables", "instructions": "Brown beef. Add onions, carrots, potatoes, broth, and herbs. Simmer 2 hours until tender.", "ingredients": [{"name": "stewing beef", "quantity": "1kg"}, {"name": "potatoes", "quantity": "4"}, {"name": "carrots", "quantity": "3"}]},
    {"name": "Pancakes", "description": "Fluffy buttermilk pancakes", "instructions": "Mix dry ingredients. Add wet. Cook on griddle until bubbles form. Flip and cook.", "ingredients": [{"name": "flour", "quantity": "2 cups"}, {"name": "buttermilk", "quantity": "2 cups"}, {"name": "eggs", "quantity": "2"}]},
    {"name": "French Onion Soup", "description": "Caramelized onion soup with cheese toast", "instructions": "Caramelize onions. Add broth and herbs. Simmer. Top with bread and gruyere, broil.", "ingredients": [{"name": "onions", "quantity": "6"}, {"name": "beef broth", "quantity": "1.5L"}, {"name": "gruyere", "quantity": "200g"}]},
    {"name": "Chocolate Chip Cookies", "description": "Classic chewy chocolate chip cookies", "instructions": "Cream butter and sugar. Add eggs and vanilla. Mix in flour and chocolate chips. Bake 10-12 min.", "ingredients": [{"name": "butter", "quantity": "225g"}, {"name": "chocolate chips", "quantity": "300g"}, {"name": "flour", "quantity": "2.5 cups"}]},
    {"name": "Grilled Salmon", "description": "Lemon-dill grilled salmon fillets", "instructions": "Season salmon. Grill 4-5 min per side. Squeeze lemon, top with dill.", "ingredients": [{"name": "salmon fillets", "quantity": "4"}, {"name": "lemon", "quantity": "2"}, {"name": "dill", "quantity": "2 tbsp"}]},
    {"name": "Margherita Pizza", "description": "Simple tomato, mozzarella, basil pizza", "instructions": "Shape dough. Top with tomato sauce, mozzarella, basil. Bake at 250°C until crust is golden.", "ingredients": [{"name": "pizza dough", "quantity": "1 ball"}, {"name": "mozzarella", "quantity": "200g"}, {"name": "basil", "quantity": "1 bunch"}]},
    {"name": "Chicken Noodle Soup", "description": "Comforting chicken soup with noodles", "instructions": "Simmer chicken with vegetables. Shred chicken. Add noodles and cook. Season with herbs.", "ingredients": [{"name": "chicken", "quantity": "500g"}, {"name": "egg noodles", "quantity": "200g"}, {"name": "carrots", "quantity": "2"}]},
    {"name": "Guacamole", "description": "Creamy avocado dip", "instructions": "Mash avocados. Add lime, onion, cilantro, tomato, salt.", "ingredients": [{"name": "avocados", "quantity": "4"}, {"name": "lime", "quantity": "2"}, {"name": "cilantro", "quantity": "1/4 cup"}]},
    {"name": "Fish Tacos", "description": "Crispy fish with slaw in soft tortillas", "instructions": "Bread and fry fish. Make slaw. Warm tortillas. Assemble with fish, slaw, and crema.", "ingredients": [{"name": "white fish", "quantity": "500g"}, {"name": "tortillas", "quantity": "8"}, {"name": "cabbage", "quantity": "1/4 head"}]},
    {"name": "Lentil Soup", "description": "Hearty vegetarian lentil soup", "instructions": "Saute onion and carrot. Add lentils, broth, cumin. Simmer 30 min. Add lemon.", "ingredients": [{"name": "red lentils", "quantity": "300g"}, {"name": "vegetable broth", "quantity": "1L"}, {"name": "cumin", "quantity": "1 tsp"}]},
    {"name": "Omelette", "description": "Fluffy cheese omelette", "instructions": "Beat eggs. Pour into hot buttered pan. When set, add cheese, fold, slide onto plate.", "ingredients": [{"name": "eggs", "quantity": "3"}, {"name": "cheese", "quantity": "50g"}, {"name": "butter", "quantity": "1 tbsp"}]},
    {"name": "Caprese Salad", "description": "Tomato, mozzarella, basil with balsamic", "instructions": "Slice tomatoes and mozzarella. Arrange with basil. Drizzle olive oil and balsamic.", "ingredients": [{"name": "tomatoes", "quantity": "4"}, {"name": "mozzarella", "quantity": "200g"}, {"name": "basil", "quantity": "1 bunch"}]},
    {"name": "Thai Green Curry", "description": "Aromatic coconut curry", "instructions": "Fry curry paste. Add coconut milk, vegetables, protein. Simmer. Serve with rice.", "ingredients": [{"name": "green curry paste", "quantity": "3 tbsp"}, {"name": "coconut milk", "quantity": "400ml"}, {"name": "chicken", "quantity": "400g"}]},
    {"name": "Bolognese", "description": "Rich Italian meat sauce", "instructions": "Soften onion, carrot, celery. Add beef, brown. Add wine, tomatoes. Simmer 2 hours.", "ingredients": [{"name": "ground beef", "quantity": "500g"}, {"name": "tomatoes", "quantity": "800g"}, {"name": "carrot", "quantity": "1"}]},
    {"name": "Hummus", "description": "Creamy chickpea dip", "instructions": "Blend chickpeas, tahini, garlic, lemon, olive oil until smooth.", "ingredients": [{"name": "chickpeas", "quantity": "400g"}, {"name": "tahini", "quantity": "3 tbsp"}, {"name": "lemon", "quantity": "2"}]},
    {"name": "Pad Thai", "description": "Stir-fried rice noodles", "instructions": "Soak noodles. Stir fry tofu or shrimp. Add noodles and sauce. Toss with peanuts and lime.", "ingredients": [{"name": "rice noodles", "quantity": "300g"}, {"name": "tamarind paste", "quantity": "2 tbsp"}, {"name": "peanuts", "quantity": "50g"}]},
    {"name": "Roast Chicken", "description": "Crispy whole roast chicken", "instructions": "Season chicken. Roast at 200°C for 1-1.5 hours. Rest 15 min.", "ingredients": [{"name": "whole chicken", "quantity": "1.5kg"}, {"name": "olive oil", "quantity": "2 tbsp"}, {"name": "herbs", "quantity": "2 tbsp"}]},
    {"name": "Mushroom Risotto", "description": "Creamy rice with mushrooms", "instructions": "Toast rice. Add wine. Add broth ladle by ladle, stirring. Fold in sauteed mushrooms and parmesan.", "ingredients": [{"name": "arborio rice", "quantity": "300g"}, {"name": "mushrooms", "quantity": "300g"}, {"name": "parmesan", "quantity": "100g"}]},
    {"name": "Pulled Pork", "description": "Slow-cooked BBQ pork", "instructions": "Rub pork with spices. Slow cook 8 hours. Shred and mix with BBQ sauce.", "ingredients": [{"name": "pork shoulder", "quantity": "2kg"}, {"name": "BBQ sauce", "quantity": "300ml"}, {"name": "brown sugar", "quantity": "2 tbsp"}]},
    {"name": "Coleslaw", "description": "Creamy cabbage salad", "instructions": "Shred cabbage and carrot. Mix with mayo, vinegar, sugar. Chill before serving.", "ingredients": [{"name": "cabbage", "quantity": "1/2 head"}, {"name": "mayonnaise", "quantity": "1/2 cup"}, {"name": "carrot", "quantity": "1"}]},
    {"name": "Tom Yum Soup", "description": "Spicy Thai soup", "instructions": "Boil broth with lemongrass, galangal, kaffir lime. Add shrimp and mushrooms. Add lime and chili.", "ingredients": [{"name": "shrimp", "quantity": "300g"}, {"name": "lemongrass", "quantity": "2 stalks"}, {"name": "mushrooms", "quantity": "100g"}]},
    {"name": "Quiche Lorraine", "description": "Bacon and cheese tart", "instructions": "Blind bake crust. Fry bacon. Mix eggs, cream, cheese. Add bacon, pour into crust. Bake 35 min.", "ingredients": [{"name": "pie crust", "quantity": "1"}, {"name": "bacon", "quantity": "200g"}, {"name": "eggs", "quantity": "3"}]},
    {"name": "Sushi Rolls", "description": "Rice and fish wrapped in nori", "instructions": "Season rice. Spread on nori. Add fillings. Roll tightly. Slice.", "ingredients": [{"name": "sushi rice", "quantity": "2 cups"}, {"name": "nori", "quantity": "6 sheets"}, {"name": "salmon", "quantity": "200g"}]},
    {"name": "Chili Con Carne", "description": "Spicy bean and beef chili", "instructions": "Brown beef. Add onions, spices, tomatoes, beans. Simmer 1 hour.", "ingredients": [{"name": "ground beef", "quantity": "500g"}, {"name": "kidney beans", "quantity": "400g"}, {"name": "tomatoes", "quantity": "400g"}]},
    {"name": "Garlic Bread", "description": "Crispy bread with garlic butter", "instructions": "Mix butter, garlic, parsley. Spread on bread. Bake 10 min until golden.", "ingredients": [{"name": "baguette", "quantity": "1"}, {"name": "butter", "quantity": "100g"}, {"name": "garlic", "quantity": "4 cloves"}]},
    {"name": "Banana Bread", "description": "Moist banana loaf", "instructions": "Mash bananas. Mix with flour, sugar, eggs, butter. Bake 1 hour at 180°C.", "ingredients": [{"name": "bananas", "quantity": "4"}, {"name": "flour", "quantity": "2 cups"}, {"name": "sugar", "quantity": "1 cup"}]},
    {"name": "Cobb Salad", "description": "Layered salad with egg, bacon, avocado", "instructions": "Arrange lettuce, chicken, bacon, egg, avocado, blue cheese in rows. Serve with dressing.", "ingredients": [{"name": "lettuce", "quantity": "1 head"}, {"name": "chicken", "quantity": "200g"}, {"name": "avocado", "quantity": "1"}]},
    {"name": "Lasagna", "description": "Layered pasta with meat and cheese", "instructions": "Layer sauce, noodles, ricotta, mozzarella. Repeat. Bake covered 45 min, uncover 15 min.", "ingredients": [{"name": "lasagna noodles", "quantity": "12"}, {"name": "ricotta", "quantity": "500g"}, {"name": "ground beef", "quantity": "500g"}]},
    {"name": "Tuna Salad", "description": "Canned tuna with mayo and celery", "instructions": "Drain tuna. Mix with mayo, celery, onion. Season. Serve on bread or greens.", "ingredients": [{"name": "canned tuna", "quantity": "2 cans"}, {"name": "mayonnaise", "quantity": "1/4 cup"}, {"name": "celery", "quantity": "2 stalks"}]},
    {"name": "Garlic Shrimp", "description": "Pan-seared shrimp in garlic butter", "instructions": "Heat butter. Add garlic. Add shrimp, cook 2 min per side. Add lemon and parsley.", "ingredients": [{"name": "shrimp", "quantity": "500g"}, {"name": "garlic", "quantity": "6 cloves"}, {"name": "butter", "quantity": "4 tbsp"}]},
    {"name": "Vegetable Soup", "description": "Simple mixed vegetable soup", "instructions": "Saute onion. Add chopped vegetables and broth. Simmer 20 min. Season.", "ingredients": [{"name": "mixed vegetables", "quantity": "500g"}, {"name": "vegetable broth", "quantity": "1L"}, {"name": "onion", "quantity": "1"}]},
    {"name": "Fried Rice", "description": "Day-old rice with egg and vegetables", "instructions": "Scramble egg, set aside. Stir fry rice. Add vegetables, soy sauce. Add egg back.", "ingredients": [{"name": "cooked rice", "quantity": "4 cups"}, {"name": "eggs", "quantity": "2"}, {"name": "soy sauce", "quantity": "2 tbsp"}]},
    {"name": "Nachos", "description": "Loaded tortilla chips with cheese", "instructions": "Layer chips and cheese. Bake until melted. Top with beans, salsa, guac, sour cream.", "ingredients": [{"name": "tortilla chips", "quantity": "200g"}, {"name": "cheddar", "quantity": "200g"}, {"name": "black beans", "quantity": "1 can"}]},
    {"name": "Miso Soup", "description": "Japanese fermented soybean soup", "instructions": "Make dashi. Add miso paste. Add tofu and seaweed. Serve with green onion.", "ingredients": [{"name": "miso paste", "quantity": "3 tbsp"}, {"name": "tofu", "quantity": "150g"}, {"name": "wakame", "quantity": "1 tbsp"}]},
    {"name": "Potato Salad", "description": "Creamy potato salad with egg", "instructions": "Boil potatoes and eggs. Cool and chop. Mix with mayo, mustard, celery.", "ingredients": [{"name": "potatoes", "quantity": "1kg"}, {"name": "mayonnaise", "quantity": "1/2 cup"}, {"name": "eggs", "quantity": "3"}]},
    {"name": "Lemonade", "description": "Fresh squeezed lemonade", "instructions": "Juice lemons. Dissolve sugar in water. Mix with lemon juice. Add ice.", "ingredients": [{"name": "lemons", "quantity": "8"}, {"name": "sugar", "quantity": "1 cup"}, {"name": "water", "quantity": "1L"}]},
    {"name": "Chicken Wings", "description": "Crispy buffalo-style wings", "instructions": "Bake or fry wings until crispy. Toss in hot sauce and butter mixture.", "ingredients": [{"name": "chicken wings", "quantity": "1kg"}, {"name": "hot sauce", "quantity": "1/2 cup"}, {"name": "butter", "quantity": "4 tbsp"}]},
    {"name": "Ratatouille", "description": "Provencal vegetable stew", "instructions": "Layer eggplant, zucchini, tomato. Bake with garlic and herbs.", "ingredients": [{"name": "eggplant", "quantity": "1"}, {"name": "zucchini", "quantity": "2"}, {"name": "tomatoes", "quantity": "4"}]},
    {"name": "Eggplant Parmesan", "description": "Breaded eggplant with tomato and cheese", "instructions": "Slice, bread, fry eggplant. Layer with sauce and mozzarella. Bake 25 min.", "ingredients": [{"name": "eggplant", "quantity": "2"}, {"name": "mozzarella", "quantity": "300g"}, {"name": "tomato sauce", "quantity": "400ml"}]},
    {"name": "Chicken Fried Rice", "description": "Stir-fried rice with chicken", "instructions": "Cook chicken, set aside. Scramble egg. Stir fry rice. Add chicken, vegetables, soy sauce.", "ingredients": [{"name": "chicken", "quantity": "300g"}, {"name": "rice", "quantity": "4 cups"}, {"name": "soy sauce", "quantity": "3 tbsp"}]},
    {"name": "Minestrone", "description": "Italian vegetable and pasta soup", "instructions": "Saute vegetables. Add broth, tomatoes, beans, pasta. Simmer until pasta is done.", "ingredients": [{"name": "pasta", "quantity": "100g"}, {"name": "cannellini beans", "quantity": "400g"}, {"name": "vegetables", "quantity": "500g"}]},
    {"name": "Cornbread", "description": "Southern-style cornbread", "instructions": "Mix cornmeal, flour, buttermilk, egg. Pour into hot cast iron. Bake 20 min.", "ingredients": [{"name": "cornmeal", "quantity": "1 cup"}, {"name": "flour", "quantity": "1 cup"}, {"name": "buttermilk", "quantity": "1 cup"}]},
    {"name": "Smoothie Bowl", "description": "Thick smoothie topped with fruit", "instructions": "Blend frozen fruit with banana and milk. Pour into bowl. Top with granola and fruit.", "ingredients": [{"name": "frozen berries", "quantity": "2 cups"}, {"name": "banana", "quantity": "1"}, {"name": "granola", "quantity": "1/2 cup"}]},
    {"name": "BLT Sandwich", "description": "Bacon, lettuce, tomato", "instructions": "Toast bread. Layer bacon, lettuce, tomato. Add mayo. Serve.", "ingredients": [{"name": "bacon", "quantity": "6 strips"}, {"name": "tomato", "quantity": "1"}, {"name": "bread", "quantity": "2 slices"}]},
    {"name": "Pesto Pasta", "description": "Basil pesto with pasta", "instructions": "Cook pasta. Toss with pesto, parmesan, and pasta water.", "ingredients": [{"name": "pasta", "quantity": "400g"}, {"name": "pesto", "quantity": "1 jar"}, {"name": "parmesan", "quantity": "50g"}]},
    {"name": "Gnocchi", "description": "Potato dumplings", "instructions": "Boil and mash potatoes. Mix with flour and egg. Shape, boil until float.", "ingredients": [{"name": "potatoes", "quantity": "1kg"}, {"name": "flour", "quantity": "200g"}, {"name": "egg", "quantity": "1"}]},
    {"name": "Creme Brulee", "description": "Creamy custard with caramelized sugar", "instructions": "Heat cream with vanilla. Whisk into egg yolks and sugar. Bake in water bath. Caramelize sugar on top.", "ingredients": [{"name": "heavy cream", "quantity": "500ml"}, {"name": "egg yolks", "quantity": "6"}, {"name": "sugar", "quantity": "100g"}]},
    {"name": "Apple Crisp", "description": "Baked apples with oat topping", "instructions": "Slice apples into dish. Mix oats, flour, butter, sugar for topping. Bake 45 min.", "ingredients": [{"name": "apples", "quantity": "6"}, {"name": "oats", "quantity": "1 cup"}, {"name": "butter", "quantity": "100g"}]},
    {"name": "Gazpacho", "description": "Cold Spanish tomato soup", "instructions": "Blend tomatoes, cucumber, pepper, bread, garlic, olive oil. Chill. Serve cold.", "ingredients": [{"name": "tomatoes", "quantity": "1kg"}, {"name": "cucumber", "quantity": "1"}, {"name": "bread", "quantity": "2 slices"}]},
    {"name": "Chicken Quesadilla", "description": "Cheese and chicken in tortilla", "instructions": "Layer tortilla with cheese and chicken. Fold. Cook in pan until golden and melted.", "ingredients": [{"name": "tortillas", "quantity": "4"}, {"name": "chicken", "quantity": "300g"}, {"name": "cheese", "quantity": "200g"}]},
    {"name": "Shepherd's Pie", "description": "Meat and vegetable topped with mashed potato", "instructions": "Cook ground meat with vegetables. Top with mashed potato. Bake 30 min.", "ingredients": [{"name": "ground lamb", "quantity": "500g"}, {"name": "potatoes", "quantity": "1kg"}, {"name": "peas", "quantity": "200g"}]},
    {"name": "Cabbage Rolls", "description": "Stuffed cabbage with meat and rice", "instructions": "Blanch cabbage leaves. Fill with meat-rice mixture. Roll. Simmer in tomato sauce.", "ingredients": [{"name": "cabbage", "quantity": "1 head"}, {"name": "ground beef", "quantity": "500g"}, {"name": "rice", "quantity": "1 cup"}]},
    {"name": "Zucchini Bread", "description": "Moist zucchini loaf", "instructions": "Grate zucchini. Mix with flour, sugar, eggs, oil. Bake 1 hour.", "ingredients": [{"name": "zucchini", "quantity": "2"}, {"name": "flour", "quantity": "3 cups"}, {"name": "sugar", "quantity": "1.5 cups"}]},
]


def main():
    created = 0
    for recipe in RECIPES:
        try:
            data = json.dumps(recipe).encode("utf-8")
            req = urllib.request.Request(
                f"{API_BASE}/recipe/",
                data=data,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req) as resp:
                result = json.load(resp)
                created += 1
                print(f"Created: {recipe['name']} (id: {result['recipe_id']})")
        except urllib.error.HTTPError as e:
            print(f"Error creating {recipe['name']}: {e.code} {e.reason}")
        except urllib.error.URLError as e:
            print(f"Error: {e.reason}. Is the backend running at {API_BASE}?")
            break
    print(f"\nDone. Created {created} recipes.")


if __name__ == "__main__":
    main()
